### PR TITLE
stiltstation check for corresponding icos station

### PR DESCRIPTION
**Pull request by claudiodonofrio**
Main changes are:
- update availability table, such that only 'real' icos station get an icos id
- add icos sampling height to the icos dictionary
- add corresponding data files to the icos dictionary
 
a note book to highlight the new properties are available on jupyter hub... project/cp_notebooks/stilt/

### CODE REVIEW

**Review by ukarst — CHANGES_REQUESTED** [review]
The new feature will make life a lot easier for user who want to compare stilt results and icos data.  I've tested and so far it works well. 
Just two small requests for the output as availability table:
- sort the stations returned in avail alphabetically
- include the ICOS (=real) sampling height in the table
We might want to help the users to select an appropriate ICOS product from the list. Could be done in an example, e.g. update ex6cSTILT_timeseries.

**Comment by claudiodonofrio** [comment]
- [x] sampling height added to availability table
- [x] sorting of availability table by name
Listing of corresponding data object has been moved into the stilstation object, because of perforance issues while searching for stiltstations. Hence new, you can list data objects with station.get_dobj_list()
the testnotebook project/cp_notebooks/stilt/ has been adapted accordingly.

**Review by ukarst — CHANGES_REQUESTED** [review]
Introducing station.get_dobj_list() in the stilt module was a good idea. No performance issues anymore. 
The returned list of data objects can get very long due to the daily NRT radon files. Nothing we can do about this. But would it be an option to filter by tracer or project or spec in get_dobj_list() ? Probably something for a new issue...

Consider setting avail_per_stn['ICOS alt'] = '' for non-ICOS stations to avoid NaN in availability table.

**Comment by altix** [comment]
Maybe it is better to use a string-value for the `ICOS alt`
image

**Comment by claudiodonofrio** [comment]
The availability table column 'ICOS alt' is now a string and the 'nan' values are removed.
The suggestion to provide the possibility to filter the data objects is a good idea, but not feasible in the timeframe for release 0.1.18. Hence i suggest to open a new issue for 0.1.19.

**Review by ukarst — APPROVED** [review]

**Pull request merged**
