### PR TITLE
66 implement carbon portal authentication for pylib

### PR DESCRIPTION
**Pull request by ZogopZ**
Please, have a look at the updated documentation as well!

### CODE REVIEW

**Review by altix — COMMENTED** [review]
I have tested locally and on explore test. 

Just one questions: Should we really give `warning` even though the user runs the code with correct authentication of from the jupyter server?
Sure, there is a description on how to ignore the warnings, but it might be a bit confusing like if something in the user procedure was wrong.

**Comment by ukarst** [comment]
It may be good to remind the user that it is the Carbon Portal MyCP username and password that should be entered. They might be confused which of their many passwords for our services they should use.

**Comment by altix** [comment]
> It may be good to remind the user that it is the Carbon Portal MyCP username and password that should be entered. They might be confused which of their many passwords for our services they should use.

There is a link in the documentation to the login-entry.

**Comment by ukarst** [comment]
> There is a link in the documentation to the login-entry.

The authentication is well described in the documentation. But a returning user who is just running a notebook might have forgotten which username/password combination was requested.

**Review by ukarst — COMMENTED** [review]
The documentation is very useful.

The formatting of the documentation in modules.md seems a bit shifted in authentication-using-username-and-password and further down.

In case of wrong username or password, the response could be a bit more user friendly - if possible. 
Screenshot 2023-02-28 at 10 25 26
The same applies if the user provides a wrong token or has a typo in the token.

**Comment by ukarst** [comment]
The warning message says: `...starting from the next version, user authentication might be required.` but in fact it is the current version and it has started.

**Review by ukarst — APPROVED** [review]
all user-friendly error messages now

**Pull request merged**
